#!/usr/bin/env bash
# Installs nginx and configures it
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
new_string="server_name _;\n\trewrite ^\/redirect_me youtube.com permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
service nginx start
