#!/usr/bin/env bash
# Installs nginx and configures it
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
new_string="server_name _;\n\trewrite ^\/redirect_me youtube.com permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
service nginx start
