#!/usr/bin/env bash
# Install load balancer with port 80
echo -e "\e[92mInstall haproxy\e[0m"
sudo apt-get -y update && sudo apt-get -y install haproxy

HAPROXY_PATH="/etc/haproxy/haproxy.cfg"

CONFIG="
frontend <ip-servidor-1>
    bind 0:80
    default_backend backend_config

backend backend_config
    balance roundrobin
    server web-01 35.185.114.184:80
    server web-02 34.75.131.28:80"

echo "$CONFIG" >> "$HAPROXY_PATH"

echo -e "\e[92mRestart haproxy\e[0m"
sudo /etc/init.d/haproxy restart
