#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy=1.8.\*
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 2713-web-01 35.185.114.184:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 2713-web-01 35.185.114.184:80 check/a         server 2713-web-02 34.75.131.28:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start
