#!/usr/bin/env bash
# Display numbers from 1  to 10 with "while"

i=1
while [ $i -le 10 ]
do
	if [ $i = 4 ]
	then
		echo "bad luck"
	elif [ $i = 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	let i+=1
done
