#!/usr/bin/env bash
# Display "Holberton School" ten times with "while"

hours=0
while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo $minutes
		let minutes+=1
	done
	let hours+=1
done
