#!/usr/bin/env bash
# File test for the holbertonschool file

file_name="holbertonschool"
if [ -e $file_name ]
then
	echo "holbertonschool file exists"
	if [ ! -s $file_name ]
	then
		echo "holbertonschool file is empty"
	else
		echo "holbertonschool file is not empty"
	fi
	if [ -f $file_name ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
